services:
  backend:
    build: ./backend
    env_file:
      - .env
    container_name: internship-tracker-backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:${PSQL_PASSWORD}@postgres:5432/${PSQL_DATABASE}

  postgres:
    image: postgres:latest
    container_name: internship-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
