services:
  postgres:
    image: postgres:latest
    container_name: internship-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRESS_DB: ${PSQL_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
