"""added company name to application

Revision ID: 2a89684758f2
Revises: 8460177e6c26
Create Date: 2026-09-27 01:54:20.854970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a89684758f2'
down_revision: Union[str, Sequence[str], None] = '8460177e6c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('company_name', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_company_alias', 'company_alias', ['company_id', 'alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_company_alias', 'company_alias', type_='unique')
    op.drop_column('application', 'company_name')
    # ### end Alembic commands ###
