"""major revamp

Revision ID: 34690ee79fe9
Revises: 
Create Date: 2026-08-26 04:24:39.674500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34690ee79fe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=False),
    sa.Column('company_id', sa.String(length=8), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.Enum('APPLIED', 'OA', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('date_applied', sa.DateTime(timezone=True), nullable=False),
    sa.Column('loc', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=63), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_message_id', name='uq_email_provider_message')
    )
    op.create_table('email_processing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('classifier_version', sa.String(length=50), nullable=True),
    sa.Column('extractor_confidence', sa.Float(), nullable=True),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('extractor_evidence', sa.Text(), nullable=True),
    sa.Column('company_raw', sa.String(length=255), nullable=True),
    sa.Column('role_raw', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('classifier_confidence >= 0 AND classifier_confidence <= 1', name='ck_classifier_confidence'),
    sa.CheckConstraint('extractor_confidence >= 0 AND extractor_confidence <= 1', name='ck_extractor_confidence'),
    sa.ForeignKeyConstraint(['email_id'], ['email_record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('stage_event',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'OA', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('processing_id', sa.String(length=36), nullable=False),
    sa.Column('dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['processing_id'], ['email_processing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_event')
    op.drop_table('email_processing')
    op.drop_table('email_record')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('company')
    # ### end Alembic commands ###
