"""created initial schema

Revision ID: 572d4cf4e7b6
Revises: 
Create Date: 2026-08-16 05:32:13.614654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572d4cf4e7b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('linkedin_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('google_refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=8), nullable=False),
    sa.Column('company_id', sa.String(length=8), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('stage', sa.Enum('APPLIED', 'OA', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=True),
    sa.Column('date_applied', sa.DateTime(), nullable=False),
    sa.Column('loc', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_event',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'OA', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstage'), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_event')
    op.drop_table('email_record')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('company')
    # ### end Alembic commands ###
