"""made company compulsory for application

Revision ID: 8ea061b7a25e
Revises: 6665d5cc801a
Create Date: 2026-08-28 04:15:52.725296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea061b7a25e'
down_revision: Union[str, Sequence[str], None] = '6665d5cc801a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_alias',
    sa.Column('company_id', sa.String(length=8), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('company_id', 'alias')
    )
    op.alter_column('application', 'company_id',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'company_id',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.drop_table('company_alias')
    # ### end Alembic commands ###
