"""added application thread and manuel review item tables2

Revision ID: 9ecad79e83f5
Revises: f17eb1c294b9
Create Date: 2026-09-03 04:50:56.799760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecad79e83f5'
down_revision: Union[str, Sequence[str], None] = 'f17eb1c294b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_thread',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'provider', 'provider_thread_id')
    )
    op.create_table('manual_review_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('candidate_application_ids', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email_processing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('email_record', sa.Column('provider_thread_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_record', 'provider_thread_id')
    op.drop_table('manual_review_item')
    op.drop_table('application_thread')
    # ### end Alembic commands ###
