"""updated manual review item table

Revision ID: c1d296ceaa09
Revises: 9ecad79e83f5
Create Date: 2026-09-04 01:19:19.827863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d296ceaa09'
down_revision: Union[str, Sequence[str], None] = '9ecad79e83f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    review_type_enum = sa.Enum(
        'APPLICATION_MATCH',
        'COMPANY_MATCH',
        name='manualreviewtype',
    )

    review_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('manual_review_item', sa.Column('review_type', sa.Enum('APPLICATION_MATCH', 'COMPANY_MATCH', name='manualreviewtype'), nullable=False))
    op.add_column('manual_review_item', sa.Column('candidates', sa.JSON(), nullable=True))
    op.add_column('manual_review_item', sa.Column('resolution', sa.String(length=100), nullable=True))
    op.add_column('manual_review_item', sa.Column('selected_id', sa.String(length=50), nullable=True))
    op.add_column('manual_review_item', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('manual_review_item', 'email_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('manual_review_item', 'reason',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('manual_review_item', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('manual_review_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('manual_review_item', 'candidate_application_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_review_item', sa.Column('candidate_application_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('manual_review_item', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('manual_review_item', 'resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('manual_review_item', 'reason',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('manual_review_item', 'email_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('manual_review_item', 'resolved_at')
    op.drop_column('manual_review_item', 'selected_id')
    op.drop_column('manual_review_item', 'resolution')
    op.drop_column('manual_review_item', 'candidates')
    op.drop_column('manual_review_item', 'review_type')
    # ### end Alembic commands ###
