"""made email_record.text and email_record.html nullable

Revision ID: e930329dce34
Revises: 572d4cf4e7b6
Create Date: 2026-08-16 21:55:22.610466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e930329dce34'
down_revision: Union[str, Sequence[str], None] = '572d4cf4e7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_record', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('email_record', 'raw_html',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_record', 'raw_html',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('email_record', 'raw_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
