"""added foreign key in company_alias.company_id

Revision ID: f17eb1c294b9
Revises: 8ea061b7a25e
Create Date: 2026-08-28 04:27:07.890628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17eb1c294b9'
down_revision: Union[str, Sequence[str], None] = '8ea061b7a25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'company_alias', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_alias', type_='foreignkey')
    # ### end Alembic commands ###
